apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: employee-portal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: ghcr.io/rathan005/employee-frontend:latest

          ports:
            - containerPort: 80

          imagePullPolicy: Always