name: Employee Portal CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BackEnd

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run test --if-present

  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build

  docker-build:

    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend

    steps:

      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build -t employee-backend ./BackEnd

      - name: Build Frontend Image
        run: |
          docker build -t employee-frontend ./Frontend


  trivy-scan:

    runs-on: ubuntu-latest

    needs:
      - docker-build

    steps:

      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build -t employee-backend ./BackEnd

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: employee-backend
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1